/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Book { 
    id?: string;
    createBy?: string;
    updateBy?: string;
    createDate?: string;
    lastModified?: string;
    isDeleted?: boolean;
    name?: string;
    author?: string;
}

